### ISSUE TITLE
iPhone12,1 16.0 - failed!!!

### ISSUE THREAD

**Issue by P5-2005** [Lrdsnow/kfd_offsets#7]
```
[info_init]: kfd->info.env.pid = 386
[info_init]: kfd->info.env.tid = 5804
[info_init]: kfd->info.env.maxfilesperproc = 10240
[info_init]: kfd->info.env.kern_version = Darwin Kernel Version 22.0.0: Tue Aug 16 20:50:57 PDT 2022; root:xnu-8792.2.11.0.1~1/RELEASE_ARM64_T8030
[info_init]: kfd->info.env.vid = 0
[puaf_init]: method_name = smith
[krkw_init]: method_name = kread_sem_open
[krkw_init]: method_name = kwrite_sem_open
[puaf_helper_give_ppl_pages]: given_ppl_pages = 210
[puaf_helper_give_ppl_pages]: 🟢 0s 3ms 314us
[puaf_run]: 🟢 0s 11ms 219us
[krkw_helper_grab_free_pages]: grabbed_free_pages = 28904
[krkw_helper_grab_free_pages]: 🟢 0s 338ms 702us
[krkw_helper_run_allocate]: 🟢 0s 4ms 294us
[krkw_helper_run_allocate]: kread ---> object_id = 1470, object_uaddr = 0x00000003d25f4000, object_size = 16, allocated_id = 2048/10140, batch_size = 1024
[0x0000]: ffffffe26baccca0 0000000000000000 
```

**Comment by Lrdsnow** [comment]
Have you tried puaf physpuppet? or changing t1sz_boot to 26ull instead of 25ull? Note, 25ull should be good but if it still doesn't work with physpuppet

**Comment by P5-2005** [comment]
i put 25ull and change vmap_HDR to 10 same issue, i tried only smith didn't tried physpuppet tbh

**Comment by Lrdsnow** [comment]
I recommend when trying anything iOS 16.4 or lower using physpuppet

**Comment by P5-2005** [comment]
tried physpuppet i get issue on console Xcode like one header not exist idk

**Comment by P5-2005** [comment]
I'm doing this on dynamic info:         ._vm_map__hdr__links__prev = 0x00 + 0x10,
        ._vm_map__hdr__links__next = 0x08 + 0x10,
        ._vm_map__hdr__links__start = 0x10 + 0x10,
        ._vm_map__hdr__links__end = 0x18 + 0x10,

**Comment by P5-2005** [comment]
i think from ios16,4 all offset should work, less than that will panic, need manual fix

**Comment by Lrdsnow** [comment]
Should work now with the vm_map fix

**Comment by P5-2005** [comment]
> Should work now with the vm_map fix
i was always doing this on vm_map_hdr, less than ios 16.4 still getting panic, so this cannot be a fix for such issue
